spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:9011/hero_cycle
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
